# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  web:prepare:
    cmds:
      - echo "Intalling all required dependencies"
      #TODO: node, pnpm, turso, kubctl, kind
  web:db:push:
    cmd: cd ./app/web && pnpm db:push
    silent: true
  web:dev:
    cmd: pnpm dev